# Generated by Django 5.0 on 2024-01-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_remove_user_bio_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
