# Generated by Django 5.0 on 2024-01-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_user_bio_user_created_at_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='defaultPic.png', upload_to='avatars'),
        ),
    ]
