# Generated by Django 4.2 on 2024-01-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='pong/defaultPic.png', upload_to='avatars'),
        ),
    ]
