# Generated by Django 4.2 on 2024-01-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
    ]
